wooahan-agile/idu-market-next

- Data/HeaderMenuData.js
- Data/NoticeSliderData.js
- components/Footer/Footer.js
- components/Header/DropMenu.js
- components/Header/Header.js
- components/HomePage/Articles.js
- components/HomePage/Function.js
- components/HomePage/Introduce.js
- components/HomePage/MainBanner.js
- components/HomePage/Notice.js
- package.json
- pages/_app.js
- pages/index.js
- scss/base/_reset.scss
- scss/helpers/_variables.scss
- scss/layout/_footer.scss
- scss/layout/_header.scss
- scss/layout/home/_articles.scss
- scss/layout/home/_funtion.scss
- scss/layout/home/_introduce.scss
- scss/layout/home/_mainBanner.scss
- scss/layout/home/_notice.scss
- scss/main.scss
- yarn.lock
issue : #2
CRA로 만든 Home Page Next.js 로 변경
> [homePage] Home Page

- app/components/Comment/ReplyComment.js
- app/components/Comment/SingleComment.js
- app/components/Trade/TradeComplete.js
- app/pages/watchlist/[studentId].js
- app/redux/sagas/boardSaga.js
- app/redux/sagas/tradeSaga.js
- app/scss/layout/_header.scss
- app/scss/layout/board/_boardDetailImage.scss
- app/scss/layout/home/_notice.scss
> [tradeComplete] Trade Complete

- app/components/Profile/ProfileUpdate.js
- app/pages/students/[studentId]/update.js
- app/redux/reducers/profileReducer.js
- app/redux/sagas/profileSaga.js
- app/scss/layout/profile/_profileUpdate.scss
> Profile update

- app/components/Board/MarketListItem.js
- app/pages/sale-list/[studentId].js
- app/pages/students/[studentId].js
- app/scss/layout/board/_market.scss
- app/scss/layout/watchlist/_watchlist.scss
> [saleList] Sale List

- app/pages/purchase-list/[studentId].js
- app/scss/layout/board/_market.scss
> [purchaseList] Purchase List

- app/Data/HeaderMenuData.js
- app/components/Header/Header.js
- app/pages/findPwd.js
- app/scss/layout/_header.scss
> [header] Header

- app/pages/404.js
- app/scss/main.scss
- app/scss/page/_page404.scss
> [404page] 404Page

- app/components/Auth/FindIdForm.js
- app/components/Auth/FindPwdForm.js
- app/components/Auth/LoginForm.js
- app/components/Auth/PasswordReset.js
- app/components/Auth/PwdResetForm.js
- app/components/Auth/RegisterForm.js
- app/pages/api/hello.js
- app/pages/boards/[categoryName]/[num].js
- app/pages/findId.js
- app/pages/findPwd.js
- app/pages/login.js
- app/pages/register.js
- app/pages/reset/password/[token].js
> [pwdChange] Pwd Change

- app/components/Board/Basic.js
- app/components/Board/BoardDetailTop.js
- app/components/Board/MarketListItem.js
- app/components/Comment/ReplyComment.js
- app/components/Comment/SingleComment.js
- app/package-lock.json
- app/scss/layout/board/_basic.scss
- app/scss/layout/board/_boardDetail.scss
- app/scss/layout/board/_comment.scss
- app/scss/layout/board/_market.scss
> Fix(sangjun/admin): 게시글 리트스 관리자 색 변경, basic게시판 font변경 #51

- app/components/Board/Basic.js
- app/components/Board/BoardDetailImage.js
- app/components/Editor/Editor.js
- app/components/Editor/UpdateEdtior.js
- app/pages/boards/[categoryName]/[num].js
> [editor] Editor issue fix

- app/components/Notification/Notification.js
- app/components/Notification/NotificationItem.js
- app/scss/components/notification/_notification.scss
> [notification] Notification

- app/components/Board/Basic.js
- app/components/Board/BoardDetailTop.js
- app/components/Board/Market.js
- app/components/Board/MarketListItem.js
- app/components/Comment/Comment.js
- app/components/Comment/ReplyComment.js
- app/components/Comment/SingleComment.js
- app/components/Editor/Editor.js
- app/components/Editor/EditorConfig.js
- app/redux/sagas/authSaga.js
- app/redux/sagas/boardSaga.js
- app/redux/sagas/commentSaga.js
- app/redux/sagas/tradeSaga.js
- app/scss/components/board/_basic.scss
- app/scss/components/board/_market.scss
- app/scss/components/comment/_comment.scss
- app/scss/components/notification/_notification.scss
> [admin] Admin

- app/components/Auth/RegisterForm.js
- app/components/HomePage/Function.js
- app/components/HomePage/Introduce.js
- app/components/HomePage/MainBanner.js
- app/scss/components/board/_basic.scss
- app/scss/components/board/_market.scss
- app/scss/components/notification/_notification.scss
- app/scss/components/profile/_profile.scss
- app/scss/components/service/_inquiry.scss
- app/scss/components/watchlist/_watchlist.scss
- app/scss/layout/_forms.scss
- app/scss/layout/home/_articles.scss
- app/scss/layout/home/_funtion.scss
- app/scss/layout/home/_introduce.scss
- app/scss/layout/home/_mainBanner.scss
- app/scss/layout/home/_notice.scss
> [layout] Layout

- app/components/Board/Basic.js
- app/components/Board/Market.js
- app/components/Editor/Editor.js
- app/components/Editor/UpdateEdtior.js
- app/components/HomePage/Articles.js
- app/components/HomePage/Function.js
- app/components/HomePage/Introduce.js
- app/components/Loading/Loading.js
- app/pages/_app.js
- app/pages/boards/[categoryName]/[num].js
- app/pages/index.js
- app/redux/reducers/boardReducer.js
- app/redux/reducers/tradeReducer.js
- app/scss/components/comment/_comment.scss
- app/scss/components/loading/_loading.scss
- app/scss/layout/_header.scss
- app/scss/layout/home/_articles.scss
- app/scss/main.scss
> [loading]Loading

- app/Data/MajorData.js
- app/components/Auth/FindPwdForm.js
- app/components/Auth/LoginForm.js
- app/components/Auth/PwdResetForm.js
- app/components/Auth/RegisterForm.js
- app/components/Profile/ProfileUpdate.js
- app/pages/findId.js
- app/pages/findPwd.js
- app/pages/register.js
> [studentId]  로그인, 회원가입 수정 #64

- app/Data/NoticeSliderData.js
- app/components/HomePage/Notice.js
- app/pages/_document.js
- app/scss/components/watchlist/_watchlist.scss
- app/scss/layout/home/_notice.scss
> [meta]Meta

- app/components/Header/Header.js
- app/components/Notification/Notification.js
- app/components/Notification/NotificationItem.js
- app/scss/components/notification/_notification.scss
> [errorFix] Error Fix

- app/components/Board/Basic.js
- app/components/Board/Market.js
- app/components/Editor/EditorPost.js
- app/components/Editor/UpdateEdtior.js
- app/pages/boards/[categoryName]/[num].js
- app/pages/boards/[categoryName]/[num]/update.js
- app/pages/boards/book.js
- app/pages/boards/clothes.js
- app/pages/boards/device.js
- app/pages/boards/etc.js
- app/pages/boards/free.js
- app/pages/boards/notice.js
> [refactor]Refactor

- app/components/Board/BoardDetailImage.js
- app/components/Editor/Editor.js
- app/components/Editor/EditorImageUpload.js
- app/components/Editor/UpdateEdtior.js
- app/components/Profile/ProfileUpdate.js
- app/pages/boards/[categoryName]/[num].js
- app/pages/boards/book.js
- app/pages/boards/clothes.js
- app/pages/boards/device.js
- app/pages/boards/etc.js
- app/pages/boards/free.js
- app/pages/boards/notice.js
- app/pages/findId.js
- app/pages/findPwd.js
- app/pages/login.js
- app/pages/purchase-list/[studentId].js
- app/pages/register.js
- app/pages/reset/password/[token].js
- app/pages/sale-list/[studentId].js
- app/pages/watchlist/[studentId].js
- app/redux/reducers/boardReducer.js
- app/redux/sagas/authSaga.js
- app/redux/sagas/boardSaga.js
- app/redux/sagas/commentSaga.js
- app/redux/sagas/notificationSaga.js
- app/redux/sagas/profileSaga.js
- app/redux/sagas/tradeSaga.js
[api] 모든 API요청 헤더에 api-key추가 #84
> [api] 모든 API요청 헤더에 api-key추가

- app/components/Board/BoardDetailImage.js
- app/components/Editor/Editor.js
- app/components/Editor/EditorImageUpload.js
- app/pages/boards/[categoryName]/[num].js
> [Image] image 업로드

- app/Data/API_KEY.js
- app/components/Editor/Editor.js
- app/components/Editor/EditorImageUpload.js
- app/components/Editor/UpdateEdtior.js
- app/components/Profile/ProfileUpdate.js
- app/package-lock.json
- app/package.json
- app/pages/boards/[categoryName]/search.js
- app/pages/boards/book.js
- app/pages/boards/clothes.js
- app/pages/boards/device.js
- app/pages/boards/etc.js
- app/pages/boards/free.js
- app/pages/boards/notice.js
- app/pages/findId.js
- app/pages/findPwd.js
- app/pages/login.js
- app/pages/purchase-list/[studentId].js
- app/pages/register.js
- app/pages/reset/password/[token].js
- app/pages/watchlist/[studentId].js
- app/redux/sagas/authSaga.js
- app/redux/sagas/boardSaga.js
- app/redux/sagas/commentSaga.js
- app/redux/sagas/notificationSaga.js
- app/redux/sagas/profileSaga.js
- app/redux/sagas/tradeSaga.js
> [api] 모든 API 헤더 api-key값 추가

- app/components/Board/BoardDetailTop.js
- app/pages/boards/[categoryName]/[num].js
- app/redux/sagas/boardSaga.js
> Modify(sagnjun/image): NHN 이미지삭제 기능구현#93

- app/components/Footer/Footer.js
- app/components/HomePage/Articles.js
- app/components/HomePage/Circles.js
- app/components/HomePage/Function.js
- app/components/HomePage/Introduce.js
- app/components/HomePage/MainBanner.js
- app/components/HomePage/Notice.js
- app/pages/index.js
- app/scss/layout/_footer.scss
- app/scss/layout/home/_articles.scss
- app/scss/layout/home/_circles.scss
- app/scss/layout/home/_funtion.scss
- app/scss/layout/home/_introduce.scss
- app/scss/layout/home/_mainBanner.scss
- app/scss/layout/home/_notice.scss
- app/scss/main.scss
> [mainPage] MainPage UI 수정

- app/Data/NoticeSliderData.js
- app/components/HomePage/Articles.js
- app/components/HomePage/Circles.js
- app/components/HomePage/Function.js
- app/components/HomePage/Introduce.js
- app/components/HomePage/MainBanner.js
- app/components/HomePage/Notice.js
- app/package.json
- app/pages/index.js
- app/scss/common/_swiper.scss
- app/scss/layout/home/_articles.scss
- app/scss/layout/home/_circles.scss
- app/scss/layout/home/_funtion.scss
- app/scss/layout/home/_introduce.scss
- app/scss/layout/home/_mainBanner.scss
- app/scss/layout/home/_notice.scss
- app/scss/main.scss
- app/yarn.lock
> [mainPage] Main Page

- app/components/Board/BoardListTop.js
- app/components/Board/Market.js
- app/scss/components/board/_market.scss
- app/scss/layout/_header.scss
- app/scss/layout/board/_boardBanner.scss
- app/scss/layout/home/_articles.scss
- app/scss/layout/home/_circles.scss
- app/scss/layout/home/_funtion.scss
- app/scss/layout/home/_introduce.scss
- app/scss/layout/home/_mainBanner.scss
- app/scss/layout/home/_notice.scss
> [mainPage] Main page UI 수정

- app/Data/HeaderMenuData.js
- app/package-lock.json
- app/pages/boards/freemarket.js
> Add(sangjun/freemarket):무료나눔 게시판 추가 #101

- app/pages/boards/[categoryName]/[num].js
- app/pages/boards/[categoryName]/[num]/update.js
- app/pages/boards/book.js
- app/pages/boards/clothes.js
- app/pages/boards/device.js
- app/pages/boards/etc.js
- app/pages/boards/free.js
- app/pages/boards/notice.js
- app/pages/login.js
- app/redux/sagas/boardSaga.js
- app/scss/layout/_header.scss
> [boards]Boards

- app/pages/boards/[categoryName]/[num]/[studentId]/complete.js
> Fix(sangjun/status): 무료나눔 게시판 거래상태 수정#106

- app/components/Editor/Editor.js
- app/components/Profile/ProfileUpdate.js
- app/components/Service/Inquiry.js
- app/components/Trade/TradeComplete.js
- app/pages/_app.js
- app/pages/boards/[categoryName]/search.js
- app/pages/boards/book.js
- app/pages/boards/clothes.js
- app/pages/boards/device.js
- app/pages/boards/etc.js
- app/pages/boards/free.js
- app/pages/boards/freemarket.js
- app/pages/boards/notice.js
- app/pages/findId.js
- app/pages/findPwd.js
- app/pages/login.js
- app/pages/purchase-list/[studentId].js
- app/pages/register.js
- app/pages/reset/password/[token].js
- app/pages/sale-list/[studentId].js
- app/pages/watchlist/[studentId].js
- app/redux/sagas/authSaga.js
- app/redux/sagas/boardSaga.js
- app/redux/sagas/commentSaga.js
- app/redux/sagas/notificationSaga.js
- app/redux/sagas/profileSaga.js
- app/redux/sagas/tradeSaga.js
> [axios] Axios Default 설정

- app/lib/gtag.js
- app/package.json
- app/pages/_app.js
- app/pages/_document.js
- app/yarn.lock
> [Analytics] 구글 애널리틱스 적용

- app/components/Board/BoardDetailContent.js
- app/components/Board/BoardDetailImage.js
- app/components/Board/BoardDetailTop.js
- app/components/Board/BoardListItem.js
- app/components/Comment/Comment.js
- app/components/Comment/ReplyComment.js
- app/components/Comment/SingleComment.js
- app/components/Notification/Notification.js
- app/components/Profile/ProfileUpdate.js
- app/hooks/useGetBoardList.js
- app/hooks/useGetMarketList.js
- app/hooks/useGetProfileBoardList.js
- app/pages/_app.js
- app/pages/boards/book.js
- app/pages/boards/clothes.js
- app/pages/boards/device.js
- app/pages/boards/etc.js
- app/pages/boards/freemarket.js
- app/pages/purchase-list/[studentId].js
- app/pages/sale-list/[studentId].js
- app/pages/service/inquiry.js
- app/pages/watchlist/[studentId].js
> [Refactor] 리팩토링 

- app/hooks/useGetBasicBoardList.js
- app/pages/boards/device.js
- app/pages/boards/free.js
- app/pages/boards/notice.js
> [refactor] 리팩토링
